# pages/export.py — Export finalized schedule (CSV / Excel / PDF / ZIP).

from __future__ import annotations
import io
import sys
import zipfile
from pathlib import Path

import pandas as pd
import streamlit as st

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))
from helpers.paths import data_dir

st.header("Export Schedule")

dd = data_dir()
schedule_path = dd / "schedule_phase2.csv"
produced_path = dd / "produced_vs_bounds.csv"
cip_path = dd / "cip_windows.csv"
val_path = dd / "validation_report.txt"

if not schedule_path.exists():
    st.info("No schedule to export. Run the solver first.")
    st.stop()

# ── Provenance banner ───────────────────────────────────────────────────
source = st.session_state.get("schedule_source", "solver")
if source == "sandbox":
    st.warning("This schedule was **manually edited** in the Sandbox.")
else:
    st.success("This schedule was generated by the **solver**.")

st.divider()

# ── Individual CSV downloads ────────────────────────────────────────────
st.subheader("CSV Downloads")
c1, c2, c3 = st.columns(3)

with c1:
    data = schedule_path.read_bytes()
    st.download_button("Schedule CSV", data=data, file_name="schedule_phase2.csv", mime="text/csv")

with c2:
    if produced_path.exists():
        st.download_button("Demand Adherence CSV", data=produced_path.read_bytes(),
                           file_name="produced_vs_bounds.csv", mime="text/csv")

with c3:
    if cip_path.exists():
        st.download_button("CIP Windows CSV", data=cip_path.read_bytes(),
                           file_name="cip_windows.csv", mime="text/csv")

# ── Excel workbook ──────────────────────────────────────────────────────
st.divider()
st.subheader("Excel Workbook")
st.caption("Combined workbook with Schedule, Demand Adherence, CIP Windows, and Changeover Summary.")

if st.button("Generate Excel", key="gen_xlsx"):
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        sched_df = pd.read_csv(schedule_path)
        sched_df.to_excel(writer, sheet_name="Schedule", index=False)

        if produced_path.exists():
            pd.read_csv(produced_path).to_excel(writer, sheet_name="Demand Adherence", index=False)

        if cip_path.exists():
            pd.read_csv(cip_path).to_excel(writer, sheet_name="CIP Windows", index=False)

        # Changeover summary
        from gantt_viewer import load_schedule, compute_changeovers
        try:
            sdf = load_schedule(schedule_path)
            _, co_df = compute_changeovers(sdf)
            co_df.to_excel(writer, sheet_name="Changeover Summary", index=False)
        except Exception:
            pass

    st.download_button(
        "Download Excel",
        data=buf.getvalue(),
        file_name="flowstate_schedule.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

# ── Gantt PDF ───────────────────────────────────────────────────────────
st.divider()
st.subheader("Gantt PDF")

if st.button("Generate Gantt PDF", key="gen_pdf"):
    try:
        from gantt_viewer import load_schedule, load_cip_windows, build_gantt_figure
        sdf = load_schedule(schedule_path)
        cdf = load_cip_windows(cip_path) if cip_path.exists() else None
        fig = build_gantt_figure(sdf, cdf, title="Flowstate Schedule")
        n_lines = sdf["Task"].nunique()
        pdf_bytes = fig.to_image(format="pdf", width=1800, height=max(600, 30 * n_lines), scale=2)
        st.download_button("Download PDF", data=pdf_bytes, file_name="flowstate_gantt.pdf", mime="application/pdf")
    except Exception as e:
        st.error(f"PDF generation failed: {e}")
        st.caption("Ensure `kaleido` is installed: `pip install kaleido`")

# ── Full ZIP package ────────────────────────────────────────────────────
st.divider()
st.subheader("Full Package (ZIP)")
st.caption("All CSVs + Gantt PDF + validation report bundled into one download.")

if st.button("Generate ZIP", key="gen_zip"):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fp in [schedule_path, produced_path, cip_path]:
            if fp.exists():
                zf.write(fp, fp.name)
        if val_path.exists():
            zf.write(val_path, val_path.name)
        # Try to include Gantt PDF
        try:
            from gantt_viewer import load_schedule, load_cip_windows, build_gantt_figure
            sdf = load_schedule(schedule_path)
            cdf = load_cip_windows(cip_path) if cip_path.exists() else None
            fig = build_gantt_figure(sdf, cdf, title="Flowstate Schedule")
            n_lines = sdf["Task"].nunique()
            pdf_bytes = fig.to_image(format="pdf", width=1800, height=max(600, 30 * n_lines), scale=2)
            zf.writestr("flowstate_gantt.pdf", pdf_bytes)
        except Exception:
            pass

    st.download_button(
        "Download ZIP",
        data=buf.getvalue(),
        file_name="flowstate_export.zip",
        mime="application/zip",
    )
